
var fontFamily = 'Nunito';
var fontWeight = 'normal';
var column = 9;
var row = 9;
var dimension = 1024;
var radius = 4;
var cutoff = 0.0;
var fontsize = dimension/column;
var tinySDFGenerator = new TinySDF(fontsize, dimension, radius, cutoff, fontFamily, fontWeight);

uniforms.grid = [column, row];

var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!?.,':éèàûôöëà";

function createParticlesWithText (text) {
	var positions = [];
	var uvs = [];
	for (var i = 0; i < text.length; i++) {
		var index = alphabet.indexOf(text[i]);
		var x = (index%column)/column;
		var y = Math.floor(index/column)/row;
		positions.push(Math.random()*2.-1., Math.random()*2.-1., Math.random()*2.-1.);
		uvs.push(x, y, i/(text.length-1));
	}

	return generateParticles({ position: positions, uv: uvs });
}

function createFontMap () {
	return twgl.createTexture(gl, {
		mag:gl.LINEAR,
		min:gl.LINEAR,
		format: gl.LUMINANCE,
		src:tinySDFGenerator.grid(alphabet, column, row)
	});
}

var textes = {
	'moutarde':
	'Une gamme d\'espaces pourfend la série : Le mélange de la lame, le bruit, le bronze et l\'autre avec un champ. Les feuilles de bronze utilisent le pinceau et le bruit, comme les salades ou les chats. Le condiment est équipé de grains partiels de premières espèce. Sur la tourbe ajouter différents ingrédients : vinaigre, sel, épices, confiés automatiquement.',
	'moutarde2': 'Il y a des multiples recettes en moutarde, plus ou moins de forteresses. Les plus répandues ont été remises au plus polyvalent, au goût sucré, au Dijon et à la moutarde d’Ecéne…pour apporter des grains agités. Si vous disposez de multiples sophistiqués sous forme de formules de multiplication, vous pourrez alors en savoir plus sur la fièvre du fabricant. Pauvre préparation des feuilles de moutarde l Le suffixe du garde forestier est la cruauté du navire… La moutarde en condiment n\'est pas nécessaire au chic avec une file d\'attente ou une cuite. Pour préparer la fluorescence fluorescente, avec des fluorescents rigides lourds ou des vitesses rapides. La moutarde englobe la composition de la vitalité, du fluide et des plaques de diffusion sous la même forme. D\'autre part, d\'utiliser un câble ou un code à barres, ou la ligne directe du serveur à la libération du périphérique. Venez la salade, dans les carburants avec des consommées de piments lourds rapidement…même pas un appartement. Une fois ouvert, vous n\'avez pas à vous soucier du réfrigérateur.',
}

var testtext = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,ABCDEFGHIJKLMNOPQRSTUVWXYZ!?.,';

var liquidtext = '';
var liquidcount = 1048576.;
for (var i = 0; i < liquidcount; ++i) liquidtext += 'L';

var treetext = 'TREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREETREE'